#ifndef __CAM_TIMEZONE_H__
#define __CAM_TIMEZONE_H__


static char * cam_tmzone_set2 [90][2] = {
	"None",											"none",
	"(GMT-12) International Date Line West",		"DatelineStandardTime-12",
	"(GMT-11) Midway Island, Samoa",				"UTC-11",
	"(GMT-10) Hawaii",								"HawaiianStandardTime-10",
	"(GMT-9) Alaska",								"AlaskanStandardTime-9",
	"(GMT-8) Pacific Time(US&Canada)",				"PacificStandardTime-8",
	"(GMT-8) Tijuana, Baja California",				"PacificStandardTime-8",
	"(GMT-7) Arizona",								"USMountainStandardTime-7",
	"(GMT-7) Chihuahua, La Paz, Mazatlan",		"MountainStandardTime-7",
	"(GMT-7) Mountain Time(US&Canada)",			"MountainStandardTime-7",
	"(GMT-6) Central America",					"CentralAmericaStandardTime-6",
	"(GMT-6) Central Time(US&Canada)",			"CentralStandardTime-6",
	"(GMT-6) Guadalajara, Mexico City, Monterrey", "MexicoStandardTime-6",
	"(GMT-6) Saskatchewan",						"CanadaCentralStandardTime-6",
	"(GMT-5) Bogota, Lima, Quito, Rio Branco",	"SAWesternStandardTime-5",
	"(GMT-5) Eastern Time(US&Canada)",			"EasternStandardTime-5",
	"(GMT-5) Indiana(East)",					"EasternStandardTime-5",
	"(GMT-4:30) Caracas",						"VenezuelaStandardTime-4:30",
	"(GMT-4) Atlantic Time(Canada)",			"AtlanticStandardTime-4",
	"(GMT-4) La Paz",							"SAWesternStandardTime-4",
	"(GMT-4) Manaus",							"CentralBrazilianStandardTime-4",
	"(GMT-4) Santiago",							"PacificSAStandardTime-4",
	"(GMT-3:30) Newfoundland",					"NewfoundlandStandardTime-3:30",
	"(GMT-3) Brasilia",							"E.SouthAmericaStandardTime-3",
	"(GMT-3) Buenos Aires",						"SAEasternStandardTime-3",
	"(GMT-3) Georgetown",						"SAEasternStandardTime-3",
	"(GMT-3) Greenland",						"GreenlandStandardTime-3",
	"(GMT-3) Montevideo",						"MontevideoStandardTime-3",
	"(GMT-2) Mid-Atlantic",						"Mid-AtlanticStandardTime-2",
	"(GMT-1) Azores",							"AzoresStandardTime-1",
	"(GMT-1) Cape Verde Is.",					"CapeVerdeStandardTime-1",
	"(GMT+0) Casablanca",						"MoroccoStandardTime0",
	"(GMT+0) Dublin, Edinburgh, Lisbon, London", "GMTStandardTime0",
	"(GMT+0) Monrovia, Reykjavik",				"GreenwichStandardTime0",
	"(GMT+1) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", "W.EuropeStandardTime1",
	"(GMT+1) Belgrade, Bratislava, Budapest, Ljubljana, Prague", "CentralEuropeanStandardTime1",
	"(GMT+1) Brussels, Copenhagen, Madrid, Paris", "RomanceStandardTime1",
	"(GMT+1) Sarajevo, Skopje, Warsaw, Zagreb", "CentralEuropeStandardTime1",
	"(GMT+1) West Central Africa",				"W.CentralAfricaStandardTime1",
	"(GMT+2) Amman",							"JordanStandardTime2",
	"(GMT+2) Athens, Bucharest, Istanbul",		"GTBStandardTime2",
	"(GMT+2) Beirut",							"MiddleEastStandardTime2",
	"(GMT+2) Cairo",							"EgyptStandardTime2",
	"(GMT+2) Harare, Pretoria",					"SouthAfricaStandardTime2",
	"(GMT+2) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", "FLEStandardTime2",
	"(GMT+2) Jerusalem",						"IsraelStandardTime2",
	"(GMT+2) Minsk",							"BelarusStandardTime2",
	"(GMT+2) Windhoek",							"NamibiaStandardTime2",
	"(GMT+3) Baghdad",							"ArabicStandardTime3",
	"(GMT+3) Kuwait, Riyadh",					"ArabStandardTime3",
	"(GMT+3) Moscow, St. Petersburg, Volgograd", "RussianStandardTime3",
	"(GMT+3) Nairobi",							"E.AfricaStandardTime3",
	"(GMT+3) Tbilisi",							"GeorgianStandardTime3",
	"(GMT+3:30) Tehran",						"IranStandardTime3:30",
	"(GMT+4) Abu Dhabi, Muscat",				"ArabianStandardTime4",
	"(GMT+4) Baku",								"AzerbaijanStandardTime4",
	"(GMT+4) Caucasus Standard Time",			"CaucasusStandardTime4",
	"(GMT+4) Port Louis",						"MauritiusStandardTime4",
	"(GMT+4) Yerevan",							"CaucasusStandardTime4",
	"(GMT+4:30) Kabul",							"AfghanistanStandardTime4:30",
	"(GMT+5) Ekaterinburg",						"EkaterinburgStandardTime5",
	"(GMT+5) Islamabad, Karachi",				"PakistanStandardTime5",
	"(GMT+5) Tashkent",							"WestAsiaStandardTime5",
	"(GMT+5:30) Chennai, Kolkata, Mumbai, New Delhi", "IndiaStandardTime5:30",
	"(GMT+5:30) Sri Jayawardenepura",			"SriLankaStandardTime5:30",
	"(GMT+5:45) Kathmandu",						"NepalStandardTime5:45",
	"(GMT+6) Almaty, Novosibirsk",				"CentralAsiaStandardTime6",
	"(GMT+6) Astana, Dhaka",					"BangladeshStandardTime6",
	"(GMT+6:30) Yangon(Rangoon)",				"MyanmarStandardTime6:30",
	"(GMT+7) Bangkok, Hanoi, Jakarta",			"SEAsiaStandardTime7",
	"(GMT+7) Krasnoyarsk",						"N.CentralAsiaStandardTime7",
	"(GMT+8) Beijing, Chongqing, Hong Kong, Urumqi", "ChinaStandardTime8",
	"(GMT+8) Irkutsk, Ulaan Bataar",			"NorthAsiaEastStandardTime8",
	"(GMT+8) Kuala Lumpur, Singapore",			"SingaporeStandardTime8",
	"(GMT+8) Perth",							"W.AustraliaStandardTime8",
	"(GMT+8) Taipei",							"TaipeiStandardTime8",
	"(GMT+9) Osaka, Sapporo, Tokyo",			"TokyoStandardTime9",
	"(GMT+9) Seoul",							"KoreaStandardTime9",
	"(GMT+9) Yakutsk",							"YakutskStandardTime9",
	"(GMT+9:30) Adelaide",						"Cen.AustraliaStandardTime9:30",
	"(GMT+9:30) Darwin",						"AUSCentralStandardTime9:30",
	"(GMT+10) Brisbane",						"E.AustraliaStandardTime10",
	"(GMT+10) Canberra, Melbourne, Sydney",		"AUSEasternStandardTime10",
	"(GMT+10) Guam, Port Moresby",				"WestPacificStandardTime10",
	"(GMT+10) Hobart",							"TasmaniaStandardTime10",
	"(GMT+10) Vladivostok",						"VladivostokStandardTime10",
	"(GMT+11) Magadan, Solomon Is., New Caledonia", "MagadanStandardTime11",
	"(GMT+12) Auckland, Wellington",			"NewZealandStandardTime12",
	"(GMT+12) Fiji, Kamchatka, Marshall Is.",	"FijiStandardTime12",
	"(GMT+13) Nuku'alofa",						"TongaStandardTime13"
};




static char * cam_tmzone_set [90] = {
	"None",										
	"(GMT-12) International Date Line West",	
	"(GMT-11) Midway Island, Samoa",			
	"(GMT-10) Hawaii",							
	"(GMT-9) Alaska",
	"(GMT-8) Pacific Time(US&Canada)",
	"(GMT-8) Tijuana, Baja California",
	"(GMT-7) Arizona",
	"(GMT-7) Chihuahua, La Paz, Mazatha",
	"(GMT-7) Mountain Time(US&Canada)",
	"(GMT-6) Central America",
	"(GMT-6) Central Time(US&Canada)",
	"(GMT-6) Guadalajara, Mexico City, Monterrey",
	"(GMT-6) Saskatchewan",
	"(GMT-5) Bogota, Lima, Quito, Rio Branco",
	"(GMT-5) Eastern Time(US&Canada)",
	"(GMT-5) Indiana(East)",
	"(GMT-4:30) Caracas",
	"(GMT-4) Atlantic Time(Canada)",
	"(GMT-4) La Paz",
	"(GMT-4) Manaus",
	"(GMT-4) Santiago",
	"(GMT-3:30) Newfoundland",
	"(GMT-3) Brasilia",
	"(GMT-3) Buenos Aires",
	"(GMT-3) Georgetown",
	"(GMT-3) Greenland",
	"(GMT-3) Montevideo",
	"(GMT-2) Mid-Atlantic",
	"(GMT-1) Azores",
	"(GMT-1) Cape Verde Is.",
	"(GMT+0) Casablanca",
	"(GMT+0) Dublin, Edinburgh, Lisbon, London",
	"(GMT+0) Monrovia, Reykjavik",
	"(GMT+1) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
	"(GMT+1) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
	"(GMT+1) Brussels, Copenhagen, Madrid, Paris",
	"(GMT+1) Sarajevo, Skopje, Warsaw, Zagreb",
	"(GMT+1) West Central Africa",
	"(GMT+2) Amman",
	"(GMT+2) Athens, Bucharest, Istanbul",
	"(GMT+2) Beirut",
	"(GMT+2) Cairo",
	"(GMT+2) Harare, Pretoria",
	"(GMT+2) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
	"(GMT+2) Jerusalem",
	"(GMT+2) Minsk",
	"(GMT+2) Windhoek",
	"(GMT+3) Baghdad",
	"(GMT+3) Kuwait, Riyadh",
	"(GMT+3) Moscos, St. Petersburg, Volgograd",
	"(GMT+3) Nairobi",
	"(GMT+3) Tbilisi",
	"(GMT+3:30) Tehran",
	"(GMT+4) Abu Dhabi, Muscat",
	"(GMT+4) Baku",
	"(GMT+4) Caucasus Standard Time",
	"(GMT+4) Port Louis",
	"(GMT+4) Yerevan",
	"(GMT+4:30) Kabul",
	"(GMT+5) Ekaterinburg",
	"(GMT+5) Islamabad, Karachi",
	"(GMT+5) Tashkent",
	"(GMT+5:30) Chennai, Kalkata, Mumbai, New Delhi",
	"(GMT+5:30) Sri Jayawardenepura",
	"(GMT+5:45) Kathmandu",
	"(GMT+6) Almaty, Novosibirsk",
	"(GMT+6) Astana, Dhaka",
	"(GMT+6:30) Yangon(Rangoon)",
	"(GMT+7) Bangkok, Hanoi, Jakarta",
	"(GMT+7) Krasnoyarsk",
	"(GMT+8) Beijing, Chonging, Hong Kong, Urumqi",
	"(GMT+8) Irkutsk, Ulaan Bataar",
	"(GMT+8) Kuala Lumpur, Singapore",
	"(GMT+8) Perth",
	"(GMT+8) Taipei",
	"(GMT+9) Osaka, Sapporo, Tokyo",
	"(GMT+9) Seoul",
	"(GMT+9) Yakutsk",
	"(GMT+9:30) Adelaide",
	"(GMT+9:30) Darwin",
	"(GMT+10) Brisbane",
	"(GMT+10) Canberra, Melbourne, Sydney",
	"(GMT+10) Guam, Port Moresby",
	"(GMT+10) Hobart",
	"(GMT+10) Vladivostok",
	"(GMT+11) Magadan, Solomon Is., New Caledonia",
	"(GMT+12) Auckland, Wellington",
	"(GMT+12) Fiji, Kamchatka, Marshall Is.",
	"(GMT+13) Nuku'alofa"
};

static const char * cam_tmzone_str [TMZONE_MAX][4] = {
	{"GMT-0", 			"",					"", 				""},
	{"STD+12", 			"",					"", 				""},
	{"STD+11", 			"", 				"", 				""},
	{"STD+10", 			"", 				"", 				""},
	{"STD+9",			"SMR", 				"M3.2.0/02:00",		"M11.1.0/02:00"},
	{"STD+8",			"SMR", 				"M3.2.0/02:00", 	"M11.1.0/02:00"},
	{"STD+8",			"SMR", 				"M4.1.0/02:00", 	"M10.5.0/02:00"},
	{"STD+7", 			"", 				"", 				""},
	{"STD+7",			"SMR", 				"M4.1.0/02:00", 	"M10.5.0/02:00"},
	{"STD+7",			"SMR", 				"M3.2.0/02:00", 	"M11.1.0/02:00"},
	{"STD+6", 			"", 				"", 				""},
	{"STD+6",			"SMR", 				"M3.2.0/02:00", 	"M11.1.0/02:00"},
	{"STD+6",			"SMR", 				"M4.1.0/02:00", 	"M10.5.0/02:00"},
	{"STD+6", 			"", 				"", 				""},
	{"STD+5", 			"", 				"", 				""},
	{"STD+5",			"SMR", 				"M3.2.0/02:00", 	"M11.1.0/02:00"},
	{"STD+5", 			"", 				"", 				""},
	{"STD+5:30", 		"", 				"", 				""},
	{"STD+4",			"SMR", 				"M3.2.0/02:00", 	"M11.1.0/02:00"},
	{"STD+4", 			"", 				"", 				""},
	{"STD+4",			"SMR", 				"M10.4.0/00:00", 	"M2.2.6/00:00"},
	{"STD+4",			"SMR", 				"M10.3.0/00:00", 	"M3.2.6/0:00"},
	{"STD+3:30", 		"", 				"", 				""},
	{"STD+3",			"SMR", 				"M10.4.0/00:00", 	"M2.2.6/00:00"},
	{"STD+3",			"SMR", 				"M10.4.0/00:00", 	"M3.2.6/00:00"},
	{"STD+3", 			"", 				"", 				""},
	{"STD+3",			"SMR", 				"M4.1.0/02:00", 	"M10.5.0/02:00"},
	{"STD+3",			"SMR", 				"M10.1.0/02:00", 	"M3.2.0/02:00"},
	{"STD+2",			"SMR", 				"M3.5.0/02:00", 	"M9.5.0/02:00"},
	{"STD+1",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD+1", 			"", 				"", 				""},
	{"STD+0", 			"", 				"", 				""},
	{"STD+0",			"SMR", 				"M3.5.0/01:00", 	"M10.5.0/02:00"},
	{"STD+0", 			"", 				"", 				""},
	{"STD-1",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-1",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-1",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-1",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-1", 			"", 				"", 				""},
	{"STD-2",			"SMR", 				"M3.4.4/00:00", 	"M10.5.5/01:00"},
	{"STD-2",			"SMR", 				"M3.5.0/03:00", 	"M10.5.0/04:00"},
	{"STD-2",			"SMR", 				"M3.5.0/00:00", 	"M10.5.6/00:00"},
	{"STD-2",			"SMR", 				"M4.5.5/00:00", 	"M9.5.4/00:00"},
	{"STD-2", 			"", 				"", 				""},
	{"STD-2",			"SMR", 				"M3.5.0/03:00", 	"M10.5.0/04:00"},
	{"STD-2",			"SMR", 				"M3.5.5/02:00", 	"M9.5.0/02:00"},
	{"STD-2",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-2",			"SMR", 				"M4.1.0/02:00", 	"M9.1.0/04:00"},
	{"STD-3", 			"", 				"", 				""},
	{"STD-3", 			"", 				"", 				""},
	{"STD-3",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-3", 			"", 				"", 				""},
	{"STD-3", 			"", 				"", 				""},
	{"STD-3:30",		"SMR", 				"M3.4.0/00:00", 	"M9.3.1/00:00"},
	{"STD-4", 			"", 				"", 				""},
	{"STD-4",			"SMR", 				"M3.5.0/04:00", 	"M10.5.0/05:00"},
	{"STD-4", 			"", 				"", 				""},
	{"STD-4",			"SMR", 				"M10.5.0/02:00", 	"M3.5.0/02:00"},
	{"STD-4",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-4:30", 		"", 				"", 				""},
	{"STD-5",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-5", 			"", 				"", 				""},
	{"STD-5", 			"", 				"", 				""},
	{"STD-5:30", 		"", 				"", 				""},
	{"STD-5:30", 		"", 				"", 				""},
	{"STD-5:45", 		"", 				"", 				""},
	{"STD-6",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-6", 			"", 				"", 				""},
	{"STD-6:30", 		"", 				"", 				""},
	{"STD-7", 			"", 				"", 				""},
	{"STD-7",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-8", 			"", 				"", 				""},
	{"STD-8",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-8", 			"", 				"", 				""},
	{"STD-8",			"SMR", 				"M10.5.0/02:00", 	"M3.5.0/03:00"},
	{"STD-8", 			"", 				"", 				""},
	{"STD-9", 			"", 				"", 				""},
	{"STD-9", 			"", 				"", 				""},
	{"STD-9",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-9:30",		"SMR", 				"M10.1.0/02:00", 	"M4.1.0/03:00"},
	{"STD-9:30", 		"", 				"", 				""},
	{"STD-10", 			"", 				"", 				""},
	{"STD-10",			"SMR", 				"M10.1.0/02:00", 	"M4.1.0/03:00"},
	{"STD-10", 			"", 				"", 				""},
	{"STD-10",			"SMR", 				"M10.1.0/02:00", 	"M4.1.0/03:00"},
	{"STD-10",			"SMR", 				"M3.5.0/02:00", 	"M10.5.0/03:00"},
	{"STD-11", 			"", 				"", 				""},
	{"STD-12",			"SMR", 				"M9.5.0/02:00", 	"M4.1.0/03:00"},
	{"STD-12", 			"", 				"", 				""},
	{"STD-13", 			"", 				"", 				""}
};

typedef struct _cam_timezone
{
	char*	OfficialTimezoneName;
	char*	OtherCommonTimezoneName;
	char*	StandardTime;
	char*	DaylightSavingTime;
	char*	ForStandardTime;
	int		TimezoneUsesDaylightSavingTime;
	char*	TZ;
	char*	TimezoneName;
	char*	name;
} CAM_TIMEZONE;

static CAM_TIMEZONE cam_tmzone2_str [] = {
/*
*/
{"Pacific/Niue"				,	""							,	"NUT"						,	""									,	"UTC-11"								,	0									,	"NUT11"						,	"(GMT-11) Midway Island, Samoa"								,	""},
{"Pacific/Honolulu"			,	"US/Hawaii"					,	"HAST"						,	""									,	"UTC-10"								,	0									,	"HAST10"					,	"(GMT-10) Hawaii"											,	""},
{"America/Anchorage"		,	"US/Alaska"					,	"AKST"						,	"AKDT"								,	"UTC-9"									,	1									,	"AKST9AKDT,M3.2.0,M11.1.0"	, 	"(GMT-9) Alaska"											,	""},
{"America/Los_Angeles"		,	"US/Pacific"				,	"PST"						,	"PDT"								,	"UTC-8"									,	1									,	"PST8PDT,M3.2.0,M11.1.0"	,	"(GMT-8) Pacific Time(US&Canada)"							,	""},
{"America/Tijuana"			,	""							,	"PST"						,	"PDT"								,	"UTC-8"									,	1									,	"PST8PDT,M3.2.0,M11.1.0"	,	"(GMT-8) Tijuana, Baja California"							,	""},
{"America/Phoenix"			,	"US/Arizona"				,	"MST"						,	""									,	"UTC-7"									,	0									,	"MST7"						,	"(GMT-7) Arizona"											,	""},
{"America/Denver"			,	"US/Mountain"				,	"MST"						,	"MDT"								,	"UTC-7"									,	1									,	"MST7MDT,M3.2.0,M11.1.0"	,	"(GMT-7) Chihuahua, La Paz, Mazatha"						,	""},
{"America/Mazatlan"			,	""							,	"MST"						,	"MDT"								,	"UTC-7"									,	1									,	"MST7MDT,M4.1.0,M10.5.0"	,	"(GMT-7) Mountain Time(US&Canada)"							,	""},
{"America/Chicago"			,	"US/Central"				,	"CST"						,	"CDT"								,	"UTC-6"									,	1									,	"CST6CDT,M3.2.0,M11.1.0"	,	"(GMT-6) Central Time(US&Canada)"							,	""},
{"America/Regina"			,	"Canada/Saskatchewan"		,	"CST"						,	""									,	"UTC-6"									,	0									,	"CST6"						,	"(GMT-6) Central America"									,	""},
{"America/Regina"			,	"Canada/Saskatchewan"		,	"CST"						,	""									,	"UTC-6"									,	0									,	"CST6"						,	"(GMT-6) Saskatchewan"										,	""}, 
{"America/Mexico_City"		,	""							,	"CST"						,	"CDT"								,	"UTC-6"									,	1									,	"CST6CDT,M4.1.0,M10.5.0"	,	"(GMT-6) Guadalajara, Mexico City, Monterrey"				,	""},
{"America/Bogota"			,	""							,	"COT"						,	""									,	"UTC-5"									,	0									,	"COT5"						,	"(GMT-5) Bogota, Lima, Quito, Rio Branco"					,	""},
{"America/New_York"			,	"US/Eastern"				,	"EST"						,	"EDT"								,	"UTC-5"									,	1									,	"EST5EDT,M3.2.0,M11.1.0"	,	"(GMT-5) Eastern Time(US&Canada)"							,	""},
{"America/Indiana"			,	"US/East-Indiana"			,	"EST"						,	"EDT"								,	"UTC-5"									,	1									,	"EST5EDT,M3.2.0,M11.1.0"	,	"(GMT-5) Indiana(East)"										,	""}, 
{"America/Caracas"			,	""							,	"VET"						,	""									,	"UTC-4:30"								,	0									,	"VET4:30"					,	"(GMT-4:30) Caracas"										,	""},
{"America/Halifax"			,	"Canada/Atlantic"			,	"AST"						,	"ADT"								,	"UTC-4"									,	1									,	"AST4ADT,M3.2.0,M11.1.0"	,	"(GMT-4) Atlantic Time(Canada)"								,	""},
{"America/Santiago"			,	""							,	"CLT"						,	"CLST"								,	"UTC-4"									,	1									,	"CLT4CLST,M10.2.0,M3.2.0"	,	"(GMT-4) Santiago"											,	""},
{"America/La_Paz"			,	""							,	"BOT"						,	""									,	"UTC-4"									,	0									,	"BOT4"						,	"(GMT-4) La Paz"											,	""},
{"America/La_Paz"			,	""							,	"AMT"						,	""									,	"UTC-4"									,	0									,	"AMT4"						,	"(GMT-4) Manaus"											,	""}, 
{"America/St_Johns"			,	"Canada/Newfoundland"		,	"NST"						,	"NDT"								,	"UTC-3:30"								,	1									,	"NST3:30NDT,M3.2.0,M11.1.0"	,	"(GMT-3:30) Newfoundland"									,	""},
{"America/Sao_Paulo"		,	"Brazil/East"				,	"BRT"						,	"BRST"								,	"UTC-3"									,	1									,	"BRT3BRST,M10.3.0,M2.3.0"	,	"(GMT-3) Brasilia"											,	""},
{"America/Buenos_Aires"		,	""							,	"ART"						,	"ARST"								,	"UTC-3"									,	0									,	"ART3"						,	"(GMT-3) Buenos Aires"										,	""},
{"America/Buenos_Aires"		,	""							,	"ART"						,	"ARST"								,	"UTC-3"									,	0									,	"ART3"						,	"(GMT-3) Georgetown"										,	""}, 
{"America/Godthab"			,	""							,	"WGT"						,	"WGST"								,	"UTC-3"									,	1									,	"WGT3WGST,M4.1.0,M10.5.0"	,	"(GMT-3) Greenland"											,	""},  
{"America/Montevideo"		,	""							,	"UYT"						,	"UYST"								,	"UTC-3"									,	1									,	"UYT3UYST,M10.1.0,M3.2.0"	,	"(GMT-3) Montevideo"										,	""},
{"Atlantic/South_Georgia"	,	"Atlantic/King_Edward_Point",	"GST"						,	""									,	"UTC-2"									,	0									,	"GST2"						,	"(GMT-2) Mid-Atlantic"										,	""},
{"Atlantic/Azores"			,	""							,	"AZOT"						,	"AZOST"								,	"UTC-1"									,	1									,	"AZOT1AZOST,M3.5.0,M10.5.0"	,	"(GMT-1) Azores"											,	""},
{"Atlantic/Cape_Verde"		,	"Atlantic/Praia"			,	"CVT"						,	""									,	"UTC-1"									,	0									,	"CVT1"						,	"(GMT-1) Cape Verde Is."									,	""},
{"Africa/Casablanca"		,	""							,	"WET"						,	""									,	"UTC"									,	0									,	"WET0"						,	"(GMT+0) Casablanca"										,	""},
{"UTC"						,	""							,	""							,	""									,	"UTC"									,	0									,	""							,	""															,	""},
{"Europe/London"			,	""							,	"GMT"						,	"BST"								,	"UTC"									,	1									,	"GMT+0BST,M3.5.0,M10.5.0"	,	"(GMT+0) Dublin, Edinburgh, Lisbon, London"					,	""},
{"Africa/Casablanca"		,	""							,	"GMT"						,	""									,	"UTC"									,	0									,	"GMT+0"						,	"(GMT+0) Monrovia, Reykjavik"								,	""},  
{"Europe/Berlin"			,	""							,	"CET"						,	"CEST"								,	"UTC+1"									,	1									,	"CET-1CEST,M3.5.0,M10.5.0"	,	"(GMT+1) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"	,	""},	
{"Europe/Belgrade"			,	""							,	"CET"						,	"CEST"								,	"UTC+1"									,	1									,	"CET-1CEST,M3.5.0,M10.5.0"	,	"(GMT+1) Belgrade, Bratislava, Budapest, Ljubljana, Prague"	,	""},  
{"Europe/Brussels"			,	""							,	"CET"						,	"CEST"								,	"UTC+1"									,	1									,	"CET-1CEST,M3.5.0,M10.5.0"	,	"(GMT+1) Brussels, Copenhagen, Madrid, Paris"				,	""}, 
{"Europe/Sarajevo"			,	""							,	"CET"						,	"CEST"								,	"UTC+1"									,	1									,	"CET-1CEST,M3.5.0,M10.5.0"	,	"(GMT+1) Sarajevo, Skopje, Warsaw, Zagreb"					,	""}, 
{"Africa/Kinshasa"			,	""							,	"WAT"						,	""									,	"UTC+1"									,	0									,	"WAT-1"						,	"(GMT+1) West Central Africa"								,	""},
{"Europe/Athens"			,	""							,	"EET"						,	"EEST"								,	"UTC+2"									,	1									,	"EET-2EEST,M3.4.4,M10.5.5"	,	"(GMT+2) Amman"												,	""}, 						
{"Europe/Istanbul"			,	""							,	"EET"						,	"EEST"								,	"UTC+2"									,	1									,	"EET-2EEST,M3.5.0,M10.5.0"	,	"(GMT+2) Athens, Bucharest, Istanbul"						,	""},
{"Africa/Cairo"				,	""							,	"EET"						,	"EEST"								,	"UTC+2"									,	1									,	"EET-2EEST,M3.5.0,M10.5.6"	,	"(GMT+2) Beirut"											,	""}, 
{"Africa/Cairo"				,	""							,	"EET"						,	"EEST"								,	"UTC+2"									,	0									,	"EET-2"						,	"(GMT+2) Cairo"												,	""},
{"Europe/Helsinki"			,	""							,	"EET"						,	"EEST"								,	"UTC+2"									,	1									,	"EET-2EEST,M3.5.0,M10.5.0"	,	"(GMT+2) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"		,	""}, 
{"Asia/Jerusalem"			,	""							,	"IST"						,	"IDT"								,	"UTC+2"									,	1									,	"IST-2IDT,M3.5.5,M9.4.0"	,	"(GMT+2) Jerusalem"											,	""},
{"Africa/Johannesburg"		,	""							,	"SAST"						,	""									,	"UTC+2"									,	0									,	"SAST-2"					,	"(GMT+2) Harare, Pretoria"									,	""},
{"Europe/Minsk"				,	""							,	"MSK"						,	""									,	"UTC+2"									,	1									,	"MSK-2"						,	"(GMT+2) Minsk"												,	""},   
{"Africa/Windhoek"			,	""							,	"CAT"						,	""									,	"UTC+2"									,	0									,	"CAT-2"						,	"(GMT+2) Windhoek"											,	""},  
{"Europe/Moscow"			,	""							,	"MSK"						,	"MSD"								,	"UTC+3"									,	1									, 	"MSD-3"						,	"(GMT+3) Moscos, St. Petersburg, Volgograd"					,	""},
{"Africa/Nairobi"			,	""							,	"EAT"						,	""									,	"UTC+3"									,	0									,	"EAT-3"						,	"(GMT+3) Nairobi"											,	""},
{"Africa/Nairobi"			,	""							,	"EAT"						,	""									,	"UTC+3"									,	0									,	"EAT-3"						,	"(GMT+3) Tbilisi"											,	""},
{"Asia/Baghdad"				,	""							,	"AST"						,	"ADT"								,	"UTC+3"									,	0									,	"AST-3"						,	"(GMT+3) Baghdad"											,	""},
{"Asia/Baghdad"				,	""							,	"AST"						,	"ADT"								,	"UTC+3"									,	0									,	"AST-3"						,	"(GMT+3) Kuwait, Riyadh"									,	""}, 
{"Asia/Tehran"				,	""							,	"IRST"						,	"IRDT"								,	"UTC+3:30"								,	1									,	"IRST-3:30IRDT,M3.3.3,M9.3.5",	"(GMT+3:30) Tehran"											,	""},
{"Asia/Muscat"				,	""							,	"GST"						,	""									,	"UTC+4"									,	0									,	"GST-4"						,	"(GMT+4) Abu Dhabi, Muscat"									,	""},
{"Asia/Baku"				,	""							,	"AZT"						,	"AZST"								,	"UTC+4"									,	1									,	"AZT-4AZST,M3.5.0,M10.5.0"	,	"(GMT+4) Baku"												,	""},
{"Asia/Tbilisi"				,	""							,	"GET"						,	""									,	"UTC+4"									,	0									,	"GET-4"						,	"(GMT+4) Caucasus Standard Time"							,	""},
{"Indian/Mauritius"			,	""							,	"MUT"						,	""									,	"UTC+4"									,	0									,	"MUT-4"						,	"(GMT+4) Port Louis"										,	""}, 
{"Asia/Yerevan"				,	""							,	"AMT"						,	""									,	"UTC+4"									,	0									,	"AMT-4"						,	"(GMT+4) Yerevan"											,	""}, 
{"Asia/Kabul"				,	""							,	"AFT"						,	""									,	"UTC+4:30"								,	0									,	"AFT-4:30"					,	"(GMT+4:30) Kabul"											,	""},
{"Asia/Yekaterinburg"		,	""							,	"EST"						,	""									,	"UTC+5"									,	0									,	"EST-5"						,	"(GMT+5) Ekaterinburg"										,	""},   
{"Asia/Karachi"				,	""							,	"PKT"						,	""									,	"UTC+5"									,	0									,	"PKT-5"						,	"(GMT+5) Islamabad, Karachi"								,	""},
{"Asia/Tashkent"			,	""							,	"UZT"						,	""									,	"UTC+5"									,	0									,	"UZT-5"						,	"(GMT+5) Tashkent"											,	""},
{"Asia/Kolkata"				,	""							,	"IST"						,	""									,	"UTC+5:30"								,	0									,	"IST-5:30"					,	"(GMT+5:30) Chennai, Kalkata, Mumbai, New Delhi"			,	""},
{"Asia/Colombo"				,	""							,	"IST"						,	""									,	"UTC+5:30"								,	0									,	"IST-5:30"					,	"(GMT+5:30) Sri Jayawardenepura"							,	""}, 
{"Asia/Katmandu"			,	""							,	"NPT"						,	""									,	"UTC+5:45"								,	0									,	"NPT-5:45"					,	"(GMT+5:45) Kathmandu"										,	""},
{"Asia/Almaty"				,	""							,	"ALMT"						,	""									,	"UTC+6"									,	0									,	"ALMT-6"					,	"(GMT+6) Almaty, Novosibirsk"								,	""},
{"Asia/Dhaka"				,	""							,	"BST"						,	""									,	"UTC+6"									,	0									,	"BST-6"						,	"(GMT+6) Astana, Dhaka"										,	""},
{"Asia/Rangoon"				,	"Asia/Naypyidaw"			,	"MMT"						,	""									,	"UTC+6:30"								,	0									,	"MMT-6:30"					,	"(GMT+6:30) Yangon(Rangoon)"								,	""},
{"Asia/Bangkok"				,	""							,	"ICT"						,	""									,	"UTC+7"									,	0									,	"ICT-7"						,	"(GMT+7) Bangkok, Hanoi, Jakarta"							,	""},
{"Asia/Krasnoyarsk"			,	""							,	"KRAT"						,	""									,	"UTC+7"									,	0									,	"KRAT-7"					,	"(GMT+7) Krasnoyarsk"										,	""},  
{"Asia/Hong_Kong"			,	""							,	"HKT"						,	""									,	"UTC+8"									,	0									,	"HKT-8"						,	"(GMT+8) Beijing, Chonging, Hong Kong, Urumqi"				,	""},
{"Asia/Irkutsk"				,	""							,	"IRKT"						,	""									,	"UTC+8"									,	0									,	"IRKT-8"					,	"(GMT+8) Irkutsk, Ulaan Bataar"								,	""},  
{"Asia/Singapore"			,	""							,	"SGT"						,	""									,	"UTC+8"									,	0									,	"SGT-8"						,	"(GMT+8) Kuala Lumpur, Singapore"							,	""},
{"Australia/Perth"			,	""							,	"WST"						,	"WDT"								,	"UTC+8"									,	0									,	"WST-8"						,	"(GMT+8) Perth"												,	""},
{"Asia/Taipei"				,	""							,	"CST"						,	""									,	"UTC+8"									,	0									,	"CST-8"						,	"(GMT+8) Taipei"											,	""},
{"Asia/Tokyo"				,	""							,	"JST"						,	""									,	"UTC+9"									,	0									,	"JST-9"						,	"(GMT+9) Osaka, Sapporo, Tokyo"								,	""},
{"Asia/Seoul"				,	""							,	"KST"						,	""									,	"UTC+9"									,	0									,	"KST-9"						,	"(GMT+9) Seoul"												,	""},
{"Asia/Yakutsk"				,	""							,	"YAKT"						,	""									,	"UTC+9"									,	0									,	"YAKT-9"					,	"(GMT+9) Yakutsk"											,	""},   
{"Australia/Adelaide"		,	""							,	"CST"						,	"CDT"								,	"UTC+9:30"								,	1									,	"CST-9:30CDT,M10.1.0,M4.1.0",	"(GMT+9:30) Adelaide"										,	""},
{"Australia/Darwin"			,	""							,	"CST"						,	""									,	"UTC+9:30"								,	0									,	"CST-9:30"					,	"(GMT+9:30) Darwin"											,	""},
{"Australia/Sydney"			,	""							,	"EST"						,	"EDT"								,	"UTC+10"								,	1									,	"EST-10EDT,M10.1.0,M4.1.0"	,	"(GMT+10) Canberra, Melbourne, Sydney"						,	""},
{"Pacific/Guam"				,	""							,	"ChST"						,	""									,	"UTC+10"								,	0									,	"ChST-10"					,	"(GMT+10) Guam, Port Moresby"								,	""},  
{"Australia/Hobart"			,	""							,	"AEDT"						,	"AEST"								,	"UTC+10"								,	1									,	"AEDT-10AEST,M10.1.0,M4.1.0",	"(GMT+10) Hobart"											,	""}, 
{"Asia/Vladivostok"			,	""							,	"VLAT"						,	""									,	"UTC+10"								,	0									,	"VLAT-10"					,	"(GMT+10) Vladivostok"										,	""},  
{"Australia/Brisbane"		,	""							,	"EST"						,	""									,	"UTC+10"								,	0									,	"EST-10"					,	"(GMT+10) Brisbane"											,	""},
{"Pacific/Noumea"			,	""							,	"NCT"						,	""									,	"UTC+11"								,	0									,	"NCT-11"					,	"(GMT+11) Magadan, Solomon Is., New Caledonia"				,	""},
{"Pacific/Auckland"			,	""							,	"NZST"						,	"NZDT"								,	"UTC+12"								,	1									,	"NZST-12NZDT,M9.5.0,M4.1.0"	,	"(GMT+12) Auckland, Wellington"								,	""},
{"Pacific/Kwajalein"		,	""							,	"MHT"						,	""									,	"UTC+12"								,	0									,	"MHT-12"					,	"(GMT+12) Fiji, Kamchatka, Marshall Is."					,	""},
{"Pacific/Apia"				,	"Pacific/Samoa"				,	"WST"						,	""									,	"UTC+13"								,	1									,	"WST-13WST,M9.5.0,M4.1.6"	,	"(GMT+13) Nuku'alofa"										,	""},
{"Pacific/Line_Islands"		,	""							,	"LINT"						,	""									,	"UTC+14"								,	0									,	"LINT-14"					,	"(GMT-12) International Date Line West"						,	""},
{"-"						,	"-"							,	"-"							,	"-"									,	"-"										,	0									,	"-"							,	"-"															,	"-"}
};
#endif /* __CAM_TIMEZONE_H__ */
