#ifndef _IQ_NNSC_H_
#define _IQ_NNSC_H_

#define IQ_NNSC_INFOR_ERR   0xFFFFFFFF

typedef struct _IQ_NNSC_INFO_TAB {
	UINT32 value;
	UINT32 max_value;
} IQ_NNSC_INFO_TAB;

/**
	IQ informatin selection index(iq_set_nnsc_info() or iq_get_nnsc_info())
*/
typedef enum _IQ_NNSC_ITEM {
	IQ_NNSC_ITEM_DARK_ENH_RATIO,          ///<Dark enhance ratio, data type #IQ_NNSC_DARK_ENH_RATIO
	IQ_NNSC_ITEM_CONTRAST_ENH_RATIO,      ///<Contrast enhance ratio, data type #IQ_NNSC_CONTRAST_ENH_RATIO
	IQ_NNSC_ITEM_GREEN_ENH_RATIO,         ///<Green enhance ratio, data type #IQ_NNSC_GREEN_ENH_RATIO
	IQ_NNSC_ITEM_SKIN_ENH_RATIO,          ///<Skin enhance ratio, data type #IQ_NNSC_SKIN_ENH_RATIO
	IQ_NNSC_ITEM_MAX_CNT,
	ENUM_DUMMY4WORD(IQ_NNSC_ITEM)
} IQ_NNSC_ITEM;

/**
	NNSC dark enhance ratio
*/
typedef enum _IQ_NNSC_DARK_ENH_RATIO {
	IQ_NNSC_DARK_ENH_RATIO_OFF          = 0,
	IQ_NNSC_DARK_ENH_RATIO_WEAK         = 25,
	IQ_NNSC_DARK_ENH_RATIO_NORMAL       = 50,
	IQ_NNSC_DARK_ENH_RATIO_STRONG       = 75,
	IQ_NNSC_DARK_ENH_RATIO_MAX          = 101,
	ENUM_DUMMY4WORD(IQ_NNSC_DARK_ENH_RATIO)
} IQ_NNSC_DARK_ENH_RATIO;

/**
	NNSC green enhance ratio
*/
typedef enum _IQ_NNSC_CONTRAST_ENH_RATIO {
	IQ_NNSC_CONTRAST_ENH_RATIO_OFF      = 0,
	IQ_NNSC_CONTRAST_ENH_RATIO_WEAK     = 25,
	IQ_NNSC_CONTRAST_ENH_RATIO_NORMAL   = 50,
	IQ_NNSC_CONTRAST_ENH_RATIO_STRONG   = 75,
	IQ_NNSC_CONTRAST_ENH_RATIO_MAX      = 101,
	ENUM_DUMMY4WORD(IQ_NNSC_CONTRAST_ENH_RATIO)
} IQ_NNSC_CONTRAST_ENH_RATIO;

/**
	NNSC skin enhance ratio
*/
typedef enum _IQ_NNSC_GREEN_ENH_RATIO {
	IQ_NNSC_GREEN_ENH_RATIO_OFF      = 0,
	IQ_NNSC_GREEN_ENH_RATIO_WEAK     = 25,
	IQ_NNSC_GREEN_ENH_RATIO_NORMAL   = 50,
	IQ_NNSC_GREEN_ENH_RATIO_STRONG   = 75,
	IQ_NNSC_GREEN_ENH_RATIO_MAX      = 101,
	ENUM_DUMMY4WORD(IQ_NNSC_GREEN_ENH_RATIO)
} IQ_NNSC_GREEN_ENH_RATIO;

/**
	NNSC contrast enhance ratio
*/
typedef enum _IQ_NNSC_SKIN_ENH_RATIO {
	IQ_NNSC_SKIN_ENH_RATIO_TAN      = 25,
	IQ_NNSC_SKIN_ENH_RATIO_OFF      = 50,
	IQ_NNSC_SKIN_ENH_RATIO_WHITE    = 75,
	IQ_NNSC_SKIN_ENH_RATIO_MAX      = 101,
	ENUM_DUMMY4WORD(IQ_NNSC_SKIN_ENH_RATIO)
} IQ_NNSC_SKIN_ENH_RATIO;

#endif

