#ifndef _VPET_API_H_
#define _VPET_API_H_

#if defined(__KERNEL__) || defined(__FREERTOS)
#include "vpe_alg.h"
#endif


/**
	VPE tuning item
*/
typedef enum _VPET_ITEM {
	VPET_ITEM_VERSION              = 0,///< data_type: [Get]     UINT32
	VPET_ITEM_SIZE_TAB,                ///< data_type: [Get]     VPET_INFO
	VPET_ITEM_RESERVE_02,
	VPET_ITEM_RESERVE_03,
	VPET_ITEM_RESERVE_04,
	VPET_ITEM_RESERVE_05,
	VPET_ITEM_RESERVE_06,
	VPET_ITEM_RESERVE_07,
	VPET_ITEM_RESERVE_08,
	VPET_ITEM_RESERVE_09,
	VPET_ITEM_SHARPEN_PARAM       = 10,///< data_type: [Set/Get] VPET_SHARPEN_PARAM
	VPET_ITEM_DCE_CTL_PARAM,           ///< data_type: [Set/Get] VPE_DCE_CTL_PARAM
	VPET_ITEM_GDC_PARAM,               ///< data_type: [Set/Get] VPE_GDC_PARAM
	VPET_ITEM_2DLUT_PARAM,             ///< data_type: [Set/Get] VPE_2DLUT_PARAM
	VPET_ITEM_DRT_PARAM,               ///< data_type: [Set/Get] VPE_DRT_PARAM
	VPET_ITEM_DCTG_PARAM,              ///< data_type: [Set/Get] VPE_DCTG_PARAM
	VPET_ITEM_RESERVE_16,
	VPET_ITEM_RESERVE_17,
	VPET_ITEM_RESERVE_18,
	VPET_ITEM_RESERVE_19,
	VPET_ITEM_RESERVE_20,
	VPET_ITEM_RESERVE_21,
	VPET_ITEM_RESERVE_22,
	VPET_ITEM_RESERVE_23,
	VPET_ITEM_RESERVE_24,
	VPET_ITEM_RESERVE_25,
	VPET_ITEM_RESERVE_26,
	VPET_ITEM_RESERVE_27,
	VPET_ITEM_RESERVE_28,
	VPET_ITEM_RESERVE_29,
	VPET_ITEM_RESERVE_30,
	VPET_ITEM_RESERVE_31,
	VPET_ITEM_RESERVE_32,
	VPET_ITEM_RESERVE_33,
	VPET_ITEM_RESERVE_34,
	VPET_ITEM_RESERVE_35,
	VPET_ITEM_RESERVE_36,
	VPET_ITEM_RESERVE_37,
	VPET_ITEM_RESERVE_38,
	VPET_ITEM_RESERVE_39,
	VPET_ITEM_RESERVE_40,
	VPET_ITEM_RESERVE_41,
	VPET_ITEM_RESERVE_42,
	VPET_ITEM_RESERVE_43,
	VPET_ITEM_RESERVE_44,
	VPET_ITEM_RESERVE_45,
	VPET_ITEM_RESERVE_46,
	VPET_ITEM_RESERVE_47,
	VPET_ITEM_RESERVE_48,
	VPET_ITEM_RESERVE_49,
	VPET_ITEM_MAX               = 50,
	ENUM_DUMMY4WORD(VPET_ITEM)
} VPET_ITEM;

// Struct of Parameter
typedef struct VPET_INFO {
	UINT32 size_tab[VPET_ITEM_MAX][2];
} VPET_INFO;

typedef struct _VPET_SHARPEN_PARAM {
	VPE_ID id;
	VPE_SHARPEN_PARAM sharpen;
} VPET_SHARPEN_PARAM;

typedef struct _VPET_DCE_CTL_PARAM {
	VPE_ID id;
	VPE_DCE_CTL_PARAM dce_ctl;
} VPET_DCE_CTL_PARAM;

typedef struct _VPET_GDC_PARAM {
	VPE_ID id;
	VPE_GDC_PARAM gdc;
} VPET_GDC_PARAM;

typedef struct _VPET_2DLUT_PARAM {
	VPE_ID id;
	VPE_2DLUT_PARAM lut2d;
} VPET_2DLUT_PARAM;

typedef struct _VPET_DRT_PARAM {
	VPE_ID id;
	VPE_DRT_PARAM drt;
} VPET_DRT_PARAM;

typedef struct _VPET_DCTG_PARAM {
	VPE_ID id;
	VPE_DCTG_PARAM dctg;
} VPET_DCTG_PARAM;


#endif

