#include "common.h"
#if ! defined (__UCLIBC__)

// We create softlink /etc/localtime to /usr/share/zoneinfo/XXXX for timezone.
// This is for glibc.

// File name of each timezone under /usr/share/zoneinfo/
char * tmzone_zoneifo [TMZONE_MAX] = {
	"GMT0",
	"Etc/GMT+12",
	"Pacific/Samoa",
	"US/Hawaii",
	"US/Alaska",
	"US/Pacific",
	"America/Tijuana",
	"US/Arizona",
	"America/Chihuahua",
	"US/Mountain",
	"US/Central",
	"Canada/Central",
	"America/Mexico_City",
	"Canada/Saskatchewan",
	"America/Bogota",
	"Canada/Eastern",
	"America/Indiana",
	"America/Caracas",
	"Canada/Atlantic",
	"America/La_Paz",
	"America/Manaus",
	"America/Santiago",
	"Canada/Newfoundland",
	"America/Sao_Paulo",
	"America/Argentina/Buenos_Aires",
	"Etc/GMT+3",
	"Etc/GMT+3",					// Need to fix.
	"America/Montevideo",
	"Atlantic/Azores",				// Need to fix.
	"Atlantic/Azores",
	"Atlantic/Cape_Verde",
	"Africa/Casablanca",
	"Europe/Dublin",
	"Africa/Monrovia",
	"Europe/Amsterdam",
	"Europe/Belgrade",
	"Europe/Copenhagen",
	"Europe/Sarajevo",
	"Etc/GMT-1",
	"Asia/Amman",
	"Europe/Athens",
	"Asia/Beirut",
	"Africa/Cairo",
	"Africa/Harare",
	"Europe/Helsinki",
	"Asia/Jerusalem",
	"Africa/Windhoek",
	"Europe/Minsk",
	"Asia/Baghdad",
	"Asia/Kuwait",
	"Africa/Nairobi",
	"Asia/Tehran",
	"Asia/Tbilisi",
	"Europe/Moscow",
	"Asia/Muscat",
	"Asia/Baku",
	"Etc/GMT-4",
	"Etc/GMT-4",
	"Asia/Yerevan",
	"Asia/Kabul",
	"Asia/Karachi",
	"Asia/Tashkent",
	"Etc/GMT-5",
	"Etc/GMT-5",
	"Asia/Kathmandu",
	"Etc/GMT-6",
	"Asia/Almaty",
	"Asia/Dhaka",
	"Asia/Yangon",
	"Asia/Bangkok",
	"Asia/Novosibirsk",
	"Asia/Hong_Kong",
	"Asia/Krasnoyarsk",
	"Asia/Singapore",
	"Australia/Perth",
	"Asia/Taipei",
	"Asia/Tokyo",
	"Asia/Seoul",
	"Asia/Irkutsk",
	"Australia/Adelaide",
	"Australia/Darwin",
	"Australia/Brisbane",
	"Australia/Canberra",
	"Pacific/Port_Moresby",
	"Australia/Hobart",
	"Asia/Vladivostok",
	"Asia/Magadan",
	"Pacific/Auckland",
	"Asia/Kamchatka",
	"Etc/GMT-13"
};


#endif
